###############################################################
#  Generated by:      Cadence Innovus 16.20-p002_1
#  OS:                Linux x86_64(Host ID huntress.ece.northwestern.edu)
#  Generated on:      Sun May 31 21:51:18 2026
#  Design:            bmi_chip_top
#  Command:           floorPlan -r 1.0 0.60 4 4 4 4
###############################################################

Version: 8

Head Box: 0.0000 0.0000 545.6050 543.7800
IO Box: 0.0000 0.0000 545.6050 543.7800
Core Box: 0.0000 0.0000 545.6050 543.7800
UseStdUtil: false

######################################################
#  DesignRoutingHalo: <space> <bottomLayerName> <topLayerName>
######################################################

######################################################
#  Core Rows Parameters:                             #
######################################################
Row Spacing = 0.000000
Row SpacingType = 2
Row Flip = 2
Core Row Site: CoreSite 

##############################################################################
#  DefRow: <name> <site> <x> <y> <orient> <num_x> <num_y> <step_x> <step_y>  #
##############################################################################
DefRow: ROW_0 CoreSite 0.0000 0.0000 FS 2728 1 0.2000 0.0000
DefRow: ROW_1 CoreSite 0.0000 1.7100 N 2728 1 0.2000 0.0000
DefRow: ROW_2 CoreSite 0.0000 3.4200 FS 2728 1 0.2000 0.0000
DefRow: ROW_3 CoreSite 0.0000 5.1300 N 2728 1 0.2000 0.0000
DefRow: ROW_4 CoreSite 0.0000 6.8400 FS 2728 1 0.2000 0.0000
DefRow: ROW_5 CoreSite 0.0000 8.5500 N 2728 1 0.2000 0.0000
DefRow: ROW_6 CoreSite 0.0000 10.2600 FS 2728 1 0.2000 0.0000
DefRow: ROW_7 CoreSite 0.0000 11.9700 N 2728 1 0.2000 0.0000
DefRow: ROW_8 CoreSite 0.0000 13.6800 FS 2728 1 0.2000 0.0000
DefRow: ROW_9 CoreSite 0.0000 15.3900 N 2728 1 0.2000 0.0000
DefRow: ROW_10 CoreSite 0.0000 17.1000 FS 2728 1 0.2000 0.0000
DefRow: ROW_11 CoreSite 0.0000 18.8100 N 2728 1 0.2000 0.0000
DefRow: ROW_12 CoreSite 0.0000 20.5200 FS 2728 1 0.2000 0.0000
DefRow: ROW_13 CoreSite 0.0000 22.2300 N 2728 1 0.2000 0.0000
DefRow: ROW_14 CoreSite 0.0000 23.9400 FS 2728 1 0.2000 0.0000
DefRow: ROW_15 CoreSite 0.0000 25.6500 N 2728 1 0.2000 0.0000
DefRow: ROW_16 CoreSite 0.0000 27.3600 FS 2728 1 0.2000 0.0000
DefRow: ROW_17 CoreSite 0.0000 29.0700 N 2728 1 0.2000 0.0000
DefRow: ROW_18 CoreSite 0.0000 30.7800 FS 2728 1 0.2000 0.0000
DefRow: ROW_19 CoreSite 0.0000 32.4900 N 2728 1 0.2000 0.0000
DefRow: ROW_20 CoreSite 0.0000 34.2000 FS 2728 1 0.2000 0.0000
DefRow: ROW_21 CoreSite 0.0000 35.9100 N 2728 1 0.2000 0.0000
DefRow: ROW_22 CoreSite 0.0000 37.6200 FS 2728 1 0.2000 0.0000
DefRow: ROW_23 CoreSite 0.0000 39.3300 N 2728 1 0.2000 0.0000
DefRow: ROW_24 CoreSite 0.0000 41.0400 FS 2728 1 0.2000 0.0000
DefRow: ROW_25 CoreSite 0.0000 42.7500 N 2728 1 0.2000 0.0000
DefRow: ROW_26 CoreSite 0.0000 44.4600 FS 2728 1 0.2000 0.0000
DefRow: ROW_27 CoreSite 0.0000 46.1700 N 2728 1 0.2000 0.0000
DefRow: ROW_28 CoreSite 0.0000 47.8800 FS 2728 1 0.2000 0.0000
DefRow: ROW_29 CoreSite 0.0000 49.5900 N 2728 1 0.2000 0.0000
DefRow: ROW_30 CoreSite 0.0000 51.3000 FS 2728 1 0.2000 0.0000
DefRow: ROW_31 CoreSite 0.0000 53.0100 N 2728 1 0.2000 0.0000
DefRow: ROW_32 CoreSite 0.0000 54.7200 FS 2728 1 0.2000 0.0000
DefRow: ROW_33 CoreSite 0.0000 56.4300 N 2728 1 0.2000 0.0000
DefRow: ROW_34 CoreSite 0.0000 58.1400 FS 2728 1 0.2000 0.0000
DefRow: ROW_35 CoreSite 0.0000 59.8500 N 2728 1 0.2000 0.0000
DefRow: ROW_36 CoreSite 0.0000 61.5600 FS 2728 1 0.2000 0.0000
DefRow: ROW_37 CoreSite 0.0000 63.2700 N 2728 1 0.2000 0.0000
DefRow: ROW_38 CoreSite 0.0000 64.9800 FS 2728 1 0.2000 0.0000
DefRow: ROW_39 CoreSite 0.0000 66.6900 N 2728 1 0.2000 0.0000
DefRow: ROW_40 CoreSite 0.0000 68.4000 FS 2728 1 0.2000 0.0000
DefRow: ROW_41 CoreSite 0.0000 70.1100 N 2728 1 0.2000 0.0000
DefRow: ROW_42 CoreSite 0.0000 71.8200 FS 2728 1 0.2000 0.0000
DefRow: ROW_43 CoreSite 0.0000 73.5300 N 2728 1 0.2000 0.0000
DefRow: ROW_44 CoreSite 0.0000 75.2400 FS 2728 1 0.2000 0.0000
DefRow: ROW_45 CoreSite 0.0000 76.9500 N 2728 1 0.2000 0.0000
DefRow: ROW_46 CoreSite 0.0000 78.6600 FS 2728 1 0.2000 0.0000
DefRow: ROW_47 CoreSite 0.0000 80.3700 N 2728 1 0.2000 0.0000
DefRow: ROW_48 CoreSite 0.0000 82.0800 FS 2728 1 0.2000 0.0000
DefRow: ROW_49 CoreSite 0.0000 83.7900 N 2728 1 0.2000 0.0000
DefRow: ROW_50 CoreSite 0.0000 85.5000 FS 2728 1 0.2000 0.0000
DefRow: ROW_51 CoreSite 0.0000 87.2100 N 2728 1 0.2000 0.0000
DefRow: ROW_52 CoreSite 0.0000 88.9200 FS 2728 1 0.2000 0.0000
DefRow: ROW_53 CoreSite 0.0000 90.6300 N 2728 1 0.2000 0.0000
DefRow: ROW_54 CoreSite 0.0000 92.3400 FS 2728 1 0.2000 0.0000
DefRow: ROW_55 CoreSite 0.0000 94.0500 N 2728 1 0.2000 0.0000
DefRow: ROW_56 CoreSite 0.0000 95.7600 FS 2728 1 0.2000 0.0000
DefRow: ROW_57 CoreSite 0.0000 97.4700 N 2728 1 0.2000 0.0000
DefRow: ROW_58 CoreSite 0.0000 99.1800 FS 2728 1 0.2000 0.0000
DefRow: ROW_59 CoreSite 0.0000 100.8900 N 2728 1 0.2000 0.0000
DefRow: ROW_60 CoreSite 0.0000 102.6000 FS 2728 1 0.2000 0.0000
DefRow: ROW_61 CoreSite 0.0000 104.3100 N 2728 1 0.2000 0.0000
DefRow: ROW_62 CoreSite 0.0000 106.0200 FS 2728 1 0.2000 0.0000
DefRow: ROW_63 CoreSite 0.0000 107.7300 N 2728 1 0.2000 0.0000
DefRow: ROW_64 CoreSite 0.0000 109.4400 FS 2728 1 0.2000 0.0000
DefRow: ROW_65 CoreSite 0.0000 111.1500 N 2728 1 0.2000 0.0000
DefRow: ROW_66 CoreSite 0.0000 112.8600 FS 2728 1 0.2000 0.0000
DefRow: ROW_67 CoreSite 0.0000 114.5700 N 2728 1 0.2000 0.0000
DefRow: ROW_68 CoreSite 0.0000 116.2800 FS 2728 1 0.2000 0.0000
DefRow: ROW_69 CoreSite 0.0000 117.9900 N 2728 1 0.2000 0.0000
DefRow: ROW_70 CoreSite 0.0000 119.7000 FS 2728 1 0.2000 0.0000
DefRow: ROW_71 CoreSite 0.0000 121.4100 N 2728 1 0.2000 0.0000
DefRow: ROW_72 CoreSite 0.0000 123.1200 FS 2728 1 0.2000 0.0000
DefRow: ROW_73 CoreSite 0.0000 124.8300 N 2728 1 0.2000 0.0000
DefRow: ROW_74 CoreSite 0.0000 126.5400 FS 2728 1 0.2000 0.0000
DefRow: ROW_75 CoreSite 0.0000 128.2500 N 2728 1 0.2000 0.0000
DefRow: ROW_76 CoreSite 0.0000 129.9600 FS 2728 1 0.2000 0.0000
DefRow: ROW_77 CoreSite 0.0000 131.6700 N 2728 1 0.2000 0.0000
DefRow: ROW_78 CoreSite 0.0000 133.3800 FS 2728 1 0.2000 0.0000
DefRow: ROW_79 CoreSite 0.0000 135.0900 N 2728 1 0.2000 0.0000
DefRow: ROW_80 CoreSite 0.0000 136.8000 FS 2728 1 0.2000 0.0000
DefRow: ROW_81 CoreSite 0.0000 138.5100 N 2728 1 0.2000 0.0000
DefRow: ROW_82 CoreSite 0.0000 140.2200 FS 2728 1 0.2000 0.0000
DefRow: ROW_83 CoreSite 0.0000 141.9300 N 2728 1 0.2000 0.0000
DefRow: ROW_84 CoreSite 0.0000 143.6400 FS 2728 1 0.2000 0.0000
DefRow: ROW_85 CoreSite 0.0000 145.3500 N 2728 1 0.2000 0.0000
DefRow: ROW_86 CoreSite 0.0000 147.0600 FS 2728 1 0.2000 0.0000
DefRow: ROW_87 CoreSite 0.0000 148.7700 N 2728 1 0.2000 0.0000
DefRow: ROW_88 CoreSite 0.0000 150.4800 FS 2728 1 0.2000 0.0000
DefRow: ROW_89 CoreSite 0.0000 152.1900 N 2728 1 0.2000 0.0000
DefRow: ROW_90 CoreSite 0.0000 153.9000 FS 2728 1 0.2000 0.0000
DefRow: ROW_91 CoreSite 0.0000 155.6100 N 2728 1 0.2000 0.0000
DefRow: ROW_92 CoreSite 0.0000 157.3200 FS 2728 1 0.2000 0.0000
DefRow: ROW_93 CoreSite 0.0000 159.0300 N 2728 1 0.2000 0.0000
DefRow: ROW_94 CoreSite 0.0000 160.7400 FS 2728 1 0.2000 0.0000
DefRow: ROW_95 CoreSite 0.0000 162.4500 N 2728 1 0.2000 0.0000
DefRow: ROW_96 CoreSite 0.0000 164.1600 FS 2728 1 0.2000 0.0000
DefRow: ROW_97 CoreSite 0.0000 165.8700 N 2728 1 0.2000 0.0000
DefRow: ROW_98 CoreSite 0.0000 167.5800 FS 2728 1 0.2000 0.0000
DefRow: ROW_99 CoreSite 0.0000 169.2900 N 2728 1 0.2000 0.0000
DefRow: ROW_100 CoreSite 0.0000 171.0000 FS 2728 1 0.2000 0.0000
DefRow: ROW_101 CoreSite 0.0000 172.7100 N 2728 1 0.2000 0.0000
DefRow: ROW_102 CoreSite 0.0000 174.4200 FS 2728 1 0.2000 0.0000
DefRow: ROW_103 CoreSite 0.0000 176.1300 N 2728 1 0.2000 0.0000
DefRow: ROW_104 CoreSite 0.0000 177.8400 FS 2728 1 0.2000 0.0000
DefRow: ROW_105 CoreSite 0.0000 179.5500 N 2728 1 0.2000 0.0000
DefRow: ROW_106 CoreSite 0.0000 181.2600 FS 2728 1 0.2000 0.0000
DefRow: ROW_107 CoreSite 0.0000 182.9700 N 2728 1 0.2000 0.0000
DefRow: ROW_108 CoreSite 0.0000 184.6800 FS 2728 1 0.2000 0.0000
DefRow: ROW_109 CoreSite 0.0000 186.3900 N 2728 1 0.2000 0.0000
DefRow: ROW_110 CoreSite 0.0000 188.1000 FS 2728 1 0.2000 0.0000
DefRow: ROW_111 CoreSite 0.0000 189.8100 N 2728 1 0.2000 0.0000
DefRow: ROW_112 CoreSite 0.0000 191.5200 FS 2728 1 0.2000 0.0000
DefRow: ROW_113 CoreSite 0.0000 193.2300 N 2728 1 0.2000 0.0000
DefRow: ROW_114 CoreSite 0.0000 194.9400 FS 2728 1 0.2000 0.0000
DefRow: ROW_115 CoreSite 0.0000 196.6500 N 2728 1 0.2000 0.0000
DefRow: ROW_116 CoreSite 0.0000 198.3600 FS 2728 1 0.2000 0.0000
DefRow: ROW_117 CoreSite 0.0000 200.0700 N 2728 1 0.2000 0.0000
DefRow: ROW_118 CoreSite 0.0000 201.7800 FS 2728 1 0.2000 0.0000
DefRow: ROW_119 CoreSite 0.0000 203.4900 N 2728 1 0.2000 0.0000
DefRow: ROW_120 CoreSite 0.0000 205.2000 FS 2728 1 0.2000 0.0000
DefRow: ROW_121 CoreSite 0.0000 206.9100 N 2728 1 0.2000 0.0000
DefRow: ROW_122 CoreSite 0.0000 208.6200 FS 2728 1 0.2000 0.0000
DefRow: ROW_123 CoreSite 0.0000 210.3300 N 2728 1 0.2000 0.0000
DefRow: ROW_124 CoreSite 0.0000 212.0400 FS 2728 1 0.2000 0.0000
DefRow: ROW_125 CoreSite 0.0000 213.7500 N 2728 1 0.2000 0.0000
DefRow: ROW_126 CoreSite 0.0000 215.4600 FS 2728 1 0.2000 0.0000
DefRow: ROW_127 CoreSite 0.0000 217.1700 N 2728 1 0.2000 0.0000
DefRow: ROW_128 CoreSite 0.0000 218.8800 FS 2728 1 0.2000 0.0000
DefRow: ROW_129 CoreSite 0.0000 220.5900 N 2728 1 0.2000 0.0000
DefRow: ROW_130 CoreSite 0.0000 222.3000 FS 2728 1 0.2000 0.0000
DefRow: ROW_131 CoreSite 0.0000 224.0100 N 2728 1 0.2000 0.0000
DefRow: ROW_132 CoreSite 0.0000 225.7200 FS 2728 1 0.2000 0.0000
DefRow: ROW_133 CoreSite 0.0000 227.4300 N 2728 1 0.2000 0.0000
DefRow: ROW_134 CoreSite 0.0000 229.1400 FS 2728 1 0.2000 0.0000
DefRow: ROW_135 CoreSite 0.0000 230.8500 N 2728 1 0.2000 0.0000
DefRow: ROW_136 CoreSite 0.0000 232.5600 FS 2728 1 0.2000 0.0000
DefRow: ROW_137 CoreSite 0.0000 234.2700 N 2728 1 0.2000 0.0000
DefRow: ROW_138 CoreSite 0.0000 235.9800 FS 2728 1 0.2000 0.0000
DefRow: ROW_139 CoreSite 0.0000 237.6900 N 2728 1 0.2000 0.0000
DefRow: ROW_140 CoreSite 0.0000 239.4000 FS 2728 1 0.2000 0.0000
DefRow: ROW_141 CoreSite 0.0000 241.1100 N 2728 1 0.2000 0.0000
DefRow: ROW_142 CoreSite 0.0000 242.8200 FS 2728 1 0.2000 0.0000
DefRow: ROW_143 CoreSite 0.0000 244.5300 N 2728 1 0.2000 0.0000
DefRow: ROW_144 CoreSite 0.0000 246.2400 FS 2728 1 0.2000 0.0000
DefRow: ROW_145 CoreSite 0.0000 247.9500 N 2728 1 0.2000 0.0000
DefRow: ROW_146 CoreSite 0.0000 249.6600 FS 2728 1 0.2000 0.0000
DefRow: ROW_147 CoreSite 0.0000 251.3700 N 2728 1 0.2000 0.0000
DefRow: ROW_148 CoreSite 0.0000 253.0800 FS 2728 1 0.2000 0.0000
DefRow: ROW_149 CoreSite 0.0000 254.7900 N 2728 1 0.2000 0.0000
DefRow: ROW_150 CoreSite 0.0000 256.5000 FS 2728 1 0.2000 0.0000
DefRow: ROW_151 CoreSite 0.0000 258.2100 N 2728 1 0.2000 0.0000
DefRow: ROW_152 CoreSite 0.0000 259.9200 FS 2728 1 0.2000 0.0000
DefRow: ROW_153 CoreSite 0.0000 261.6300 N 2728 1 0.2000 0.0000
DefRow: ROW_154 CoreSite 0.0000 263.3400 FS 2728 1 0.2000 0.0000
DefRow: ROW_155 CoreSite 0.0000 265.0500 N 2728 1 0.2000 0.0000
DefRow: ROW_156 CoreSite 0.0000 266.7600 FS 2728 1 0.2000 0.0000
DefRow: ROW_157 CoreSite 0.0000 268.4700 N 2728 1 0.2000 0.0000
DefRow: ROW_158 CoreSite 0.0000 270.1800 FS 2728 1 0.2000 0.0000
DefRow: ROW_159 CoreSite 0.0000 271.8900 N 2728 1 0.2000 0.0000
DefRow: ROW_160 CoreSite 0.0000 273.6000 FS 2728 1 0.2000 0.0000
DefRow: ROW_161 CoreSite 0.0000 275.3100 N 2728 1 0.2000 0.0000
DefRow: ROW_162 CoreSite 0.0000 277.0200 FS 2728 1 0.2000 0.0000
DefRow: ROW_163 CoreSite 0.0000 278.7300 N 2728 1 0.2000 0.0000
DefRow: ROW_164 CoreSite 0.0000 280.4400 FS 2728 1 0.2000 0.0000
DefRow: ROW_165 CoreSite 0.0000 282.1500 N 2728 1 0.2000 0.0000
DefRow: ROW_166 CoreSite 0.0000 283.8600 FS 2728 1 0.2000 0.0000
DefRow: ROW_167 CoreSite 0.0000 285.5700 N 2728 1 0.2000 0.0000
DefRow: ROW_168 CoreSite 0.0000 287.2800 FS 2728 1 0.2000 0.0000
DefRow: ROW_169 CoreSite 0.0000 288.9900 N 2728 1 0.2000 0.0000
DefRow: ROW_170 CoreSite 0.0000 290.7000 FS 2728 1 0.2000 0.0000
DefRow: ROW_171 CoreSite 0.0000 292.4100 N 2728 1 0.2000 0.0000
DefRow: ROW_172 CoreSite 0.0000 294.1200 FS 2728 1 0.2000 0.0000
DefRow: ROW_173 CoreSite 0.0000 295.8300 N 2728 1 0.2000 0.0000
DefRow: ROW_174 CoreSite 0.0000 297.5400 FS 2728 1 0.2000 0.0000
DefRow: ROW_175 CoreSite 0.0000 299.2500 N 2728 1 0.2000 0.0000
DefRow: ROW_176 CoreSite 0.0000 300.9600 FS 2728 1 0.2000 0.0000
DefRow: ROW_177 CoreSite 0.0000 302.6700 N 2728 1 0.2000 0.0000
DefRow: ROW_178 CoreSite 0.0000 304.3800 FS 2728 1 0.2000 0.0000
DefRow: ROW_179 CoreSite 0.0000 306.0900 N 2728 1 0.2000 0.0000
DefRow: ROW_180 CoreSite 0.0000 307.8000 FS 2728 1 0.2000 0.0000
DefRow: ROW_181 CoreSite 0.0000 309.5100 N 2728 1 0.2000 0.0000
DefRow: ROW_182 CoreSite 0.0000 311.2200 FS 2728 1 0.2000 0.0000
DefRow: ROW_183 CoreSite 0.0000 312.9300 N 2728 1 0.2000 0.0000
DefRow: ROW_184 CoreSite 0.0000 314.6400 FS 2728 1 0.2000 0.0000
DefRow: ROW_185 CoreSite 0.0000 316.3500 N 2728 1 0.2000 0.0000
DefRow: ROW_186 CoreSite 0.0000 318.0600 FS 2728 1 0.2000 0.0000
DefRow: ROW_187 CoreSite 0.0000 319.7700 N 2728 1 0.2000 0.0000
DefRow: ROW_188 CoreSite 0.0000 321.4800 FS 2728 1 0.2000 0.0000
DefRow: ROW_189 CoreSite 0.0000 323.1900 N 2728 1 0.2000 0.0000
DefRow: ROW_190 CoreSite 0.0000 324.9000 FS 2728 1 0.2000 0.0000
DefRow: ROW_191 CoreSite 0.0000 326.6100 N 2728 1 0.2000 0.0000
DefRow: ROW_192 CoreSite 0.0000 328.3200 FS 2728 1 0.2000 0.0000
DefRow: ROW_193 CoreSite 0.0000 330.0300 N 2728 1 0.2000 0.0000
DefRow: ROW_194 CoreSite 0.0000 331.7400 FS 2728 1 0.2000 0.0000
DefRow: ROW_195 CoreSite 0.0000 333.4500 N 2728 1 0.2000 0.0000
DefRow: ROW_196 CoreSite 0.0000 335.1600 FS 2728 1 0.2000 0.0000
DefRow: ROW_197 CoreSite 0.0000 336.8700 N 2728 1 0.2000 0.0000
DefRow: ROW_198 CoreSite 0.0000 338.5800 FS 2728 1 0.2000 0.0000
DefRow: ROW_199 CoreSite 0.0000 340.2900 N 2728 1 0.2000 0.0000
DefRow: ROW_200 CoreSite 0.0000 342.0000 FS 2728 1 0.2000 0.0000
DefRow: ROW_201 CoreSite 0.0000 343.7100 N 2728 1 0.2000 0.0000
DefRow: ROW_202 CoreSite 0.0000 345.4200 FS 2728 1 0.2000 0.0000
DefRow: ROW_203 CoreSite 0.0000 347.1300 N 2728 1 0.2000 0.0000
DefRow: ROW_204 CoreSite 0.0000 348.8400 FS 2728 1 0.2000 0.0000
DefRow: ROW_205 CoreSite 0.0000 350.5500 N 2728 1 0.2000 0.0000
DefRow: ROW_206 CoreSite 0.0000 352.2600 FS 2728 1 0.2000 0.0000
DefRow: ROW_207 CoreSite 0.0000 353.9700 N 2728 1 0.2000 0.0000
DefRow: ROW_208 CoreSite 0.0000 355.6800 FS 2728 1 0.2000 0.0000
DefRow: ROW_209 CoreSite 0.0000 357.3900 N 2728 1 0.2000 0.0000
DefRow: ROW_210 CoreSite 0.0000 359.1000 FS 2728 1 0.2000 0.0000
DefRow: ROW_211 CoreSite 0.0000 360.8100 N 2728 1 0.2000 0.0000
DefRow: ROW_212 CoreSite 0.0000 362.5200 FS 2728 1 0.2000 0.0000
DefRow: ROW_213 CoreSite 0.0000 364.2300 N 2728 1 0.2000 0.0000
DefRow: ROW_214 CoreSite 0.0000 365.9400 FS 2728 1 0.2000 0.0000
DefRow: ROW_215 CoreSite 0.0000 367.6500 N 2728 1 0.2000 0.0000
DefRow: ROW_216 CoreSite 0.0000 369.3600 FS 2728 1 0.2000 0.0000
DefRow: ROW_217 CoreSite 0.0000 371.0700 N 2728 1 0.2000 0.0000
DefRow: ROW_218 CoreSite 0.0000 372.7800 FS 2728 1 0.2000 0.0000
DefRow: ROW_219 CoreSite 0.0000 374.4900 N 2728 1 0.2000 0.0000
DefRow: ROW_220 CoreSite 0.0000 376.2000 FS 2728 1 0.2000 0.0000
DefRow: ROW_221 CoreSite 0.0000 377.9100 N 2728 1 0.2000 0.0000
DefRow: ROW_222 CoreSite 0.0000 379.6200 FS 2728 1 0.2000 0.0000
DefRow: ROW_223 CoreSite 0.0000 381.3300 N 2728 1 0.2000 0.0000
DefRow: ROW_224 CoreSite 0.0000 383.0400 FS 2728 1 0.2000 0.0000
DefRow: ROW_225 CoreSite 0.0000 384.7500 N 2728 1 0.2000 0.0000
DefRow: ROW_226 CoreSite 0.0000 386.4600 FS 2728 1 0.2000 0.0000
DefRow: ROW_227 CoreSite 0.0000 388.1700 N 2728 1 0.2000 0.0000
DefRow: ROW_228 CoreSite 0.0000 389.8800 FS 2728 1 0.2000 0.0000
DefRow: ROW_229 CoreSite 0.0000 391.5900 N 2728 1 0.2000 0.0000
DefRow: ROW_230 CoreSite 0.0000 393.3000 FS 2728 1 0.2000 0.0000
DefRow: ROW_231 CoreSite 0.0000 395.0100 N 2728 1 0.2000 0.0000
DefRow: ROW_232 CoreSite 0.0000 396.7200 FS 2728 1 0.2000 0.0000
DefRow: ROW_233 CoreSite 0.0000 398.4300 N 2728 1 0.2000 0.0000
DefRow: ROW_234 CoreSite 0.0000 400.1400 FS 2728 1 0.2000 0.0000
DefRow: ROW_235 CoreSite 0.0000 401.8500 N 2728 1 0.2000 0.0000
DefRow: ROW_236 CoreSite 0.0000 403.5600 FS 2728 1 0.2000 0.0000
DefRow: ROW_237 CoreSite 0.0000 405.2700 N 2728 1 0.2000 0.0000
DefRow: ROW_238 CoreSite 0.0000 406.9800 FS 2728 1 0.2000 0.0000
DefRow: ROW_239 CoreSite 0.0000 408.6900 N 2728 1 0.2000 0.0000
DefRow: ROW_240 CoreSite 0.0000 410.4000 FS 2728 1 0.2000 0.0000
DefRow: ROW_241 CoreSite 0.0000 412.1100 N 2728 1 0.2000 0.0000
DefRow: ROW_242 CoreSite 0.0000 413.8200 FS 2728 1 0.2000 0.0000
DefRow: ROW_243 CoreSite 0.0000 415.5300 N 2728 1 0.2000 0.0000
DefRow: ROW_244 CoreSite 0.0000 417.2400 FS 2728 1 0.2000 0.0000
DefRow: ROW_245 CoreSite 0.0000 418.9500 N 2728 1 0.2000 0.0000
DefRow: ROW_246 CoreSite 0.0000 420.6600 FS 2728 1 0.2000 0.0000
DefRow: ROW_247 CoreSite 0.0000 422.3700 N 2728 1 0.2000 0.0000
DefRow: ROW_248 CoreSite 0.0000 424.0800 FS 2728 1 0.2000 0.0000
DefRow: ROW_249 CoreSite 0.0000 425.7900 N 2728 1 0.2000 0.0000
DefRow: ROW_250 CoreSite 0.0000 427.5000 FS 2728 1 0.2000 0.0000
DefRow: ROW_251 CoreSite 0.0000 429.2100 N 2728 1 0.2000 0.0000
DefRow: ROW_252 CoreSite 0.0000 430.9200 FS 2728 1 0.2000 0.0000
DefRow: ROW_253 CoreSite 0.0000 432.6300 N 2728 1 0.2000 0.0000
DefRow: ROW_254 CoreSite 0.0000 434.3400 FS 2728 1 0.2000 0.0000
DefRow: ROW_255 CoreSite 0.0000 436.0500 N 2728 1 0.2000 0.0000
DefRow: ROW_256 CoreSite 0.0000 437.7600 FS 2728 1 0.2000 0.0000
DefRow: ROW_257 CoreSite 0.0000 439.4700 N 2728 1 0.2000 0.0000
DefRow: ROW_258 CoreSite 0.0000 441.1800 FS 2728 1 0.2000 0.0000
DefRow: ROW_259 CoreSite 0.0000 442.8900 N 2728 1 0.2000 0.0000
DefRow: ROW_260 CoreSite 0.0000 444.6000 FS 2728 1 0.2000 0.0000
DefRow: ROW_261 CoreSite 0.0000 446.3100 N 2728 1 0.2000 0.0000
DefRow: ROW_262 CoreSite 0.0000 448.0200 FS 2728 1 0.2000 0.0000
DefRow: ROW_263 CoreSite 0.0000 449.7300 N 2728 1 0.2000 0.0000
DefRow: ROW_264 CoreSite 0.0000 451.4400 FS 2728 1 0.2000 0.0000
DefRow: ROW_265 CoreSite 0.0000 453.1500 N 2728 1 0.2000 0.0000
DefRow: ROW_266 CoreSite 0.0000 454.8600 FS 2728 1 0.2000 0.0000
DefRow: ROW_267 CoreSite 0.0000 456.5700 N 2728 1 0.2000 0.0000
DefRow: ROW_268 CoreSite 0.0000 458.2800 FS 2728 1 0.2000 0.0000
DefRow: ROW_269 CoreSite 0.0000 459.9900 N 2728 1 0.2000 0.0000
DefRow: ROW_270 CoreSite 0.0000 461.7000 FS 2728 1 0.2000 0.0000
DefRow: ROW_271 CoreSite 0.0000 463.4100 N 2728 1 0.2000 0.0000
DefRow: ROW_272 CoreSite 0.0000 465.1200 FS 2728 1 0.2000 0.0000
DefRow: ROW_273 CoreSite 0.0000 466.8300 N 2728 1 0.2000 0.0000
DefRow: ROW_274 CoreSite 0.0000 468.5400 FS 2728 1 0.2000 0.0000
DefRow: ROW_275 CoreSite 0.0000 470.2500 N 2728 1 0.2000 0.0000
DefRow: ROW_276 CoreSite 0.0000 471.9600 FS 2728 1 0.2000 0.0000
DefRow: ROW_277 CoreSite 0.0000 473.6700 N 2728 1 0.2000 0.0000
DefRow: ROW_278 CoreSite 0.0000 475.3800 FS 2728 1 0.2000 0.0000
DefRow: ROW_279 CoreSite 0.0000 477.0900 N 2728 1 0.2000 0.0000
DefRow: ROW_280 CoreSite 0.0000 478.8000 FS 2728 1 0.2000 0.0000
DefRow: ROW_281 CoreSite 0.0000 480.5100 N 2728 1 0.2000 0.0000
DefRow: ROW_282 CoreSite 0.0000 482.2200 FS 2728 1 0.2000 0.0000
DefRow: ROW_283 CoreSite 0.0000 483.9300 N 2728 1 0.2000 0.0000
DefRow: ROW_284 CoreSite 0.0000 485.6400 FS 2728 1 0.2000 0.0000
DefRow: ROW_285 CoreSite 0.0000 487.3500 N 2728 1 0.2000 0.0000
DefRow: ROW_286 CoreSite 0.0000 489.0600 FS 2728 1 0.2000 0.0000
DefRow: ROW_287 CoreSite 0.0000 490.7700 N 2728 1 0.2000 0.0000
DefRow: ROW_288 CoreSite 0.0000 492.4800 FS 2728 1 0.2000 0.0000
DefRow: ROW_289 CoreSite 0.0000 494.1900 N 2728 1 0.2000 0.0000
DefRow: ROW_290 CoreSite 0.0000 495.9000 FS 2728 1 0.2000 0.0000
DefRow: ROW_291 CoreSite 0.0000 497.6100 N 2728 1 0.2000 0.0000
DefRow: ROW_292 CoreSite 0.0000 499.3200 FS 2728 1 0.2000 0.0000
DefRow: ROW_293 CoreSite 0.0000 501.0300 N 2728 1 0.2000 0.0000
DefRow: ROW_294 CoreSite 0.0000 502.7400 FS 2728 1 0.2000 0.0000
DefRow: ROW_295 CoreSite 0.0000 504.4500 N 2728 1 0.2000 0.0000
DefRow: ROW_296 CoreSite 0.0000 506.1600 FS 2728 1 0.2000 0.0000
DefRow: ROW_297 CoreSite 0.0000 507.8700 N 2728 1 0.2000 0.0000
DefRow: ROW_298 CoreSite 0.0000 509.5800 FS 2728 1 0.2000 0.0000
DefRow: ROW_299 CoreSite 0.0000 511.2900 N 2728 1 0.2000 0.0000
DefRow: ROW_300 CoreSite 0.0000 513.0000 FS 2728 1 0.2000 0.0000
DefRow: ROW_301 CoreSite 0.0000 514.7100 N 2728 1 0.2000 0.0000
DefRow: ROW_302 CoreSite 0.0000 516.4200 FS 2728 1 0.2000 0.0000
DefRow: ROW_303 CoreSite 0.0000 518.1300 N 2728 1 0.2000 0.0000
DefRow: ROW_304 CoreSite 0.0000 519.8400 FS 2728 1 0.2000 0.0000
DefRow: ROW_305 CoreSite 0.0000 521.5500 N 2728 1 0.2000 0.0000
DefRow: ROW_306 CoreSite 0.0000 523.2600 FS 2728 1 0.2000 0.0000
DefRow: ROW_307 CoreSite 0.0000 524.9700 N 2728 1 0.2000 0.0000
DefRow: ROW_308 CoreSite 0.0000 526.6800 FS 2728 1 0.2000 0.0000
DefRow: ROW_309 CoreSite 0.0000 528.3900 N 2728 1 0.2000 0.0000
DefRow: ROW_310 CoreSite 0.0000 530.1000 FS 2728 1 0.2000 0.0000
DefRow: ROW_311 CoreSite 0.0000 531.8100 N 2728 1 0.2000 0.0000
DefRow: ROW_312 CoreSite 0.0000 533.5200 FS 2728 1 0.2000 0.0000
DefRow: ROW_313 CoreSite 0.0000 535.2300 N 2728 1 0.2000 0.0000
DefRow: ROW_314 CoreSite 0.0000 536.9400 FS 2728 1 0.2000 0.0000
DefRow: ROW_315 CoreSite 0.0000 538.6500 N 2728 1 0.2000 0.0000
DefRow: ROW_316 CoreSite 0.0000 540.3600 FS 2728 1 0.2000 0.0000
DefRow: ROW_317 CoreSite 0.0000 542.0700 N 2728 1 0.2000 0.0000

############################################################################################
#  Track: dir start number space layer_num layer1 [firstColor] [isSameColor] [width] [rule]#
############################################################################################
Track: X 0.6000 1091 0.5000 1 11
Track: Y 0.5700 1144 0.4750 1 11
Track: Y 0.0950 2862 0.1900 1 10
Track: X 0.6000 1091 0.5000 1 10
Track: X 0.1000 2728 0.2000 1 9
Track: Y 0.0950 2862 0.1900 1 9
Track: Y 0.0950 2862 0.1900 1 8
Track: X 0.1000 2728 0.2000 1 8
Track: X 0.1000 2728 0.2000 1 7
Track: Y 0.0950 2862 0.1900 1 7
Track: Y 0.0950 2862 0.1900 1 6
Track: X 0.1000 2728 0.2000 1 6
Track: X 0.1000 2728 0.2000 1 5
Track: Y 0.0950 2862 0.1900 1 5
Track: Y 0.0950 2862 0.1900 1 4
Track: X 0.1000 2728 0.2000 1 4
Track: X 0.1000 2728 0.2000 1 3
Track: Y 0.0950 2862 0.1900 1 3
Track: Y 0.0950 2862 0.1900 1 2
Track: X 0.1000 2728 0.2000 1 2
Track: X 0.1000 2728 0.2000 1 1
Track: Y 0.0950 2862 0.1900 1 1

######################################################
#  GCellGrid: dir start number space                 #
######################################################
GCellGrid: X 544.1000 2 1.5050
GCellGrid: X 0.1000 273 2.0000
GCellGrid: X 0.0000 2 0.1000
GCellGrid: Y 543.4950 2 0.2850
GCellGrid: Y 0.0950 287 1.9000
GCellGrid: Y 0.0000 2 0.0950

######################################################
#  SpareCell: cellName                               #
#  SpareInst: instName                               #
######################################################

###############################1p########################
#  <SelectiveBlockage>                                #
#     <cell name="cell_name" />                     #
#  </SelectiveBlockage                                #
#######################################################

######################################################
#  ScanGroup: groupName startPin stopPin             #
######################################################

######################################################
#  JtagCell:  leafCellName                           #
#  JtagInst:  <instName | HInstName>                 #
######################################################

#########################################################
#  PhysicalNet: <name> [-pwr|-gnd|-tiehi|-tielo]        #
#########################################################
PhysicalNet: VDD -pwr
PhysicalNet: VSS -gnd

#########################################################
#  PhysicalInstance: <name> <cell> <orient> <llx> <lly> #
#########################################################

#####################################################################
#  Group: <group_name> <nrHinst> [-isPhyHier]                       #
#    <inst_name>                                                    #
#    ...                                                            #
#####################################################################

#####################################################################
#  Fence:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Region: <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Guide:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  SoftGuide: <name>                                                #
#    ...                                                            #
#####################################################################

###########################################################################
#  <Constraints>                                                          #
#     <Constraint  type="fence|guide|region|softguide"                    #
#                  readonly=1  name="blk_name">                           #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#     </Constraint>                                                       #
#  </Constraints>                                                         #
###########################################################################
######################################################################################
#  BlackBox: -cell <cell_name> { -size <x> <y> |  -area <um^2> | \                  #
#            -gatecount <count> <areapergate> <utilization> | \                     #
#            {-gateArea <gateAreaValue> [-macroArea <macroAreaValue>]} } \          #
#            [-minwidth <w> | -minheight <h> | -fixedwidh <w> | -fixedheight <h>] \ #
#            [-aspectratio <ratio>]                                                  #
#            [-boxList <nrConstraintBox>                                             #
#              ConstraintBox: <llx> <lly> <urx> <ury>                                #
#              ... ]                                                                 #
######################################################################################

#######################################################################################
#  <Blackboxes>                                                                       #
#     <Blackbox  cell=name  width=N height=N                                          #
#                { area=A | gatecount=N areaPerGate=A cellUtil=F |                    #
#                  gateArea=F {macroArea=F | macorList='str'} includeMacroArea={0|1}} #
#                [minWidth=N | minHeight=N | fixedWidh=N | fixedHeight=N]             #
#                [aspectRatio=R] >                                                    #
#         <Box llx=float lly=float urx=float ury=float /> ...                         #
#     </Blackbox>                                                                     #
#  </Blackboxes>                                                                      #
#######################################################################################

######################################################
#  Instance: <name> <orient> <llx> <lly>             #
######################################################

#################################################################
#  Block: <name> <orient> [<llx> <lly>]                         #
#         [<haloLeftMargin>  <haloBottomMargin>                 #
#          <haloRightMargin> <haloTopMargin> <haloFromInstBox>] #
#         [<IsInstDefCovered> <IsInstPreplaced>]                #
#                                                               #
#  Block with INT_MAX loc is for recording the halo block with  #
#  non-prePlaced status                                         #
#################################################################

######################################################
#  BlockLayerObstruct: <name> <layerX> ...           #
######################################################

######################################################
#  FeedthroughBuffer: <instName>                     #
######################################################

###########################################################################
#  <HierarchicalPartitions>                                               #
#     <GlobalPinConstraints>                                              #
#         <PinSpacing spacing=val />                                      #
#         <PinWidth layer=layerId width=val />                            #
#         <PinDepth layer=layerId depth=val />                            #
#         <CornerToPinDistance distance=val />                            #
#     </GlobalPinConstraints>                                             #
#     <CellPtnCut name="name" cuts=Num >                                  #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 /> ...                  #
#     </CellPtnCut>                                                       #
#     <NetGroup name="group_name" nets=val spacing=val isOptOrder=val   #
#         isAltLayer=val isPffGroup=val isSpreadPin=val                   #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val#
#         isPureExclude=val isCompactArea=val isMixedSignal=val >         #
#         <Net name="net_name" /> ...                                   #
#     </NetGroup>                                                         #
#     <Partition name="ptn_name"  hinst="name"                            #
#         coreToLeft=fval coreToRight=fval coreToTop=fval                 #
#         coreToBottom=val pinSpacingNorth=val pinSpacingWest=val         #
#         pinSpacingSouth=val pinSpacingEast=val  blockedLayers=xval >    #
#         <TrackHalfPitch Horizontal=val Vertical=val />                  #
#         <SpacingHalo left=10.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <Clone hinst="hinst_name" orient=R0|R90|... />                  #
#         <PinLayer side="N|W|S|E" Metal1=yes Metal2=yes ... />           #
#         <RowSize cellHeight=1.0 railWidth=1.0 />                        #
#         <DefaultTechSite name="core" />                                   #
#         <RoutingHalo sideSize=11.0 bottomLayer=M1 topLayer=M2  />       #
#         <SpacingHalo left=11.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <PinToCornerDistance  totalCorners=nrCorners >                  #
#            <Corner number=<cornerNumber> distance=<distance> /> ...     #
#         </PinToCornerDistance >                                         #
#         <PinSpacingArea llx=val lly=val urx=val ury=val spacing=val />  #
#         <LayerWidthDepth layer=layerId width=w depth=d />               #
#         <PinConstraint>                                                 #
#            <Pin name="pinName" >                                      #
#               <edge2 edgeMap=val />                                    #
#               <spacing space=val />                                    #
#               <layer layerMap=xval />                                  #
#               <pinWidth width=val />                                   #
#               <pinDepth depth=val />                                   #
#               <location x=val y=val />                                 #
#            </Pin>                                                       #
#         </PinConstraint>                                                #
#     </Partition>                                                        #
#     <CellPinGroup name="group_name" cell="cell_name" pins=nr        #
#         spacing=val isOptOrder=val isAltLayer=val isSpreadPin=val       #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val#
#         isPureExclude=val isCompactArea=val >                           #
#         <GroupFTerm name="term_name" /> ...                             #
#     </CellPinGroup>                                                     #
#     <PartitionPinBlockage layerMap=x llx=1 lly=2 urx=3 ury=4 name="n" />#
#     <PinGuide name="name" boxes=num layerPriority=val cell="name" >     #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 layer=id /> ...         #
#     </PinGuide>                                                         #
#  </HierarchicalPartitions>                                              #
###########################################################################
<HierarchicalPartitions>
    <GlobalPinConstraints>
        <PinSpacing spacing=2 />
        <CornerToPinDistance distance=5 />
    </GlobalPinConstraints>
    <Partition name="bmi_chip_top" hinst="" coreToLeft=0.0000 coreToRight=0.0000 coreToTop=0.0000 coreToBottom=0.0000 pinSpacingNorth=-1 pinSpacingWest=-1 pinSpacingSouth=-1 pinSpacingEast=-1 blockedLayers=0x7ff orient=R0>
	<PinLayer side="N" Metal2=yes Metal4=yes Metal6=yes Metal8=yes Metal10=yes />
	<PinLayer side="W" Metal3=yes Metal5=yes Metal7=yes Metal9=yes Metal11=yes />
	<PinLayer side="S" Metal2=yes Metal4=yes Metal6=yes Metal8=yes Metal10=yes />
	<PinLayer side="E" Metal3=yes Metal5=yes Metal7=yes Metal9=yes Metal11=yes />
    <PinToCornerDistance totalCorners=4 >
      <Corner number=0 distance=-1 />
      <Corner number=1 distance=-1 />
      <Corner number=2 distance=-1 />
      <Corner number=3 distance=-1 />
    </PinToCornerDistance>
    </Partition>
</HierarchicalPartitions>

####################################################################################
#  <PlacementBlockages>                                                            #
#     <Blockage name="blk_name" type="hard|soft|partial">                      #
#       <Attr density=1.2 excludeFlops=yes inst="inst_name" pushdown=yes />      #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                                        #
#     </Blockage>                                                                  #
#  </PlacementBlockages>                                                           #
####################################################################################

#################################################################
#  <SizeBlockages>                                             #
#     <Blockage name="blk_name">                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                     #
#     </Blockage>                                               #
#  </SizeBlockages>                                            #
#################################################################

##########################################################################################################
#  <RouteBlockages>                                                                                      #
#     <Blockage name="blk_name" type="User|RouteGuide|PtnCut|WideWire">                              #
#       <Attr spacing=1.2 drw=1.2 inst="name" pushdown=yes fills=yes exceptpgnet=yes pgnetonly=yes />  #
#       <Layer type="route|cut|masterslice" id=layerNo />                                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                                                              #
#       <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...  />                                                      #
#     </Blockage>                                                                                        #
#  </RouteBlockages>                                                                                     #
##########################################################################################################

######################################################
#  NetWeight: <net_name> <weight (in integer)>       #
######################################################

###########################################################################################
# NetbottomPreferredRoutingLayer:  <net_name> <bottomPreferredRoutingLayer (in integer)>  #
###########################################################################################

################################################################
# NetAvoidDetour:  <net_name>  < avoidDetour  { 1| 0}>   #
################################################################

#################################################################
#  SprFile: <file_name>                                         #
#################################################################
SprFile: .bmi_chip_top3560768.rs.fp.spr

##############################################################################
#  <IOPins>                                                                  #
#    <Pin name="pin_name" type="clock|power|ground|analog"                   #
#         status="covered|fixed|placed" is_special=1 >                       #
#      <Port>                                                                #
#        <Pref x=1 y=2 side="N|S|W|E|U|D" width=w depth=d orientation=val /> #
#        <Via name="via_name" x=1 y=2 BotMask=2 CutMask=1 TopMask=2 />...  #
#        <Layer id=id spacing=1.2 drw=1.2>                                   #
#          <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#          <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...           />              #
#        </Layer> ...                                                        #
#      </Port>  ...                                                          #
#      <NETEXPR>                                                             #
#        ground VSS                                                          #
#      </NETEXPR> ...                                                        #
#      <Antenna model=num type="name" value=float_num layer=num /> ...       #
#    </Pin> ...                                                              #
#  </IOPins>                                                                 #
##############################################################################

<IOPins>
  <Pin name="clk" >
  </Pin>
  <Pin name="rst_n" >
  </Pin>
  <Pin name="adc_sample[7]" >
  </Pin>
  <Pin name="adc_sample[6]" >
  </Pin>
  <Pin name="adc_sample[5]" >
  </Pin>
  <Pin name="adc_sample[4]" >
  </Pin>
  <Pin name="adc_sample[3]" >
  </Pin>
  <Pin name="adc_sample[2]" >
  </Pin>
  <Pin name="adc_sample[1]" >
  </Pin>
  <Pin name="adc_sample[0]" >
  </Pin>
  <Pin name="adc_channel[2]" >
  </Pin>
  <Pin name="adc_channel[1]" >
  </Pin>
  <Pin name="adc_channel[0]" >
  </Pin>
  <Pin name="spi_sclk" >
  </Pin>
  <Pin name="spi_cs_n" >
  </Pin>
  <Pin name="spi_miso" >
  </Pin>
  <Pin name="scan_en" >
  </Pin>
  <Pin name="scan_clk" >
  </Pin>
  <Pin name="scan_in" >
  </Pin>
</IOPins>

#####################################################################
#  <Property>                                                       #
#     <obj_type name="inst_name" >                                  #
#       <prop name="name" type=type_name value=val />               #
#       <Attr name="name" type=type_name value=val />               #
#     </obj_type>                                                   #
#  </Property>                                                      #
#  where:                                                           #
#       type is data type: Box, String, Int, PTR, Loc, double, Bits #
#       obj_type are: inst, Design, instTerm, Bump, cell, net       #
#####################################################################
<Properties>
  <Design name="bmi_chip_top">
  </Design>
</Properties>

################################################################################
#  NetProperties: <net_name> [-special] [-def_prop {int|dbl|str} <value>]...   #
################################################################################

##################################################################################
#    Feedthru info:                                                              #
# <Feedthrus>                                                                    #
#   <Feedthru>                                                                   #
#       <tsv llx=n lly=n urx=n ury=n />                                          #
#       <stackvia layer=z llx=n lly=n urx=n ury=n />                             #
#       <bump front=name back=name  />                                           #
#   </Feedthru>                                                                  #
#   <Feedthru>                                                                   #
#   <...>                                                                        #
#   </Feedthru>                                                                  #
# </Feedthrus>                                                                   #
################################################################################
